"""English copy for the browser edition. The Japanese source stays authoritative."""

BODY = {
    '歌詞の言語': 'Lyrics language', '<option value="auto">自動判定</option>': '<option value="auto">Auto-detect</option>',
    '<button id="btnAddFont">追加</button>': '<button id="btnAddFont">Add</button>',
    '曲名': 'Song title', '自動': 'Auto',
    '曲名（タイトルカード・HUDに表示）': 'Song title (shown on title cards and HUD)',
    'アーティスト': 'Artist', '表示モード': 'Editor mode',
    'おまかせボタン中心のシンプルな画面': 'A simple workspace focused on automatic creation',
    'すべての設定を表示': 'Show all settings',
    '保存したプロジェクト(.json)を開く': 'Open a saved project (.json)',
    'プロジェクトを .json で保存': 'Save project as .json',
    'After Effects パネル用の構成データを書き出す': 'Export project data for the After Effects panel',
    '出力物の権利とライセンス': 'Rights and licenses for your exports',
    '歌詞とタイミング': 'Lyrics and timing', 'スタイルと書き出し': 'Style and export',
    '歌詞（1行 = 1フレーズ）': 'Lyrics (one phrase per line)',
    '1行が1フレーズ。空行は少し間を空けます': 'One phrase per line. A blank line adds a short pause.',
    '夜明けの色を/覚えてる': 'I remember/the dawn',
    'でカットの切れ目を指定': 'marks a cut boundary',
    '… 強調（大きく・インパクト寄りの演出）': '… emphasis (larger, stronger effects)',
    '… フラッシュと揺れを入れる': '… adds a flash and shake',
    '… 注釈レイアウトの小さな文字': '… smaller text in annotation layouts',
    '… LRC のタイムスタンプをそのまま使用': '… uses an LRC timestamp',
    'で始まる行 … コメント（無視）': 'starts a comment (ignored)',
    '行末の': 'A trailing', '透明': 'transparent', '歌詞|ruby or note': 'lyrics|reading or note',
    '歌詞': 'Lyrics', '曲とタイミング': 'Audio and timing',
    '曲なし（読み込むと拍を検出してカットを合わせます）': 'No audio. Import a song to detect beats and align cuts.',
    'mp3 / wav / m4a など': 'MP3, WAV, M4A and more',
    '曲を読み込む': 'Import audio', '曲を再生しながら各行の頭でタップ': 'Tap at the start of each line while the song plays',
    'タップで同期': 'Tap to sync', '開始(秒)': 'Start (s)', '行の長さ': 'Line duration',
    '拍にスナップ': 'Snap to beat', '手動タイミングを消す': 'Clear manual timing',
    '曲に合わせて、各行が始まる瞬間に': 'Press', 'かボタンを押してください。': 'or the button as each line starts.',
    '次:': 'Next:', '終了する': 'Finish', '行とカット': 'Lines and cuts',
    '再生位置': 'Playback position', 'タイムライン（クリックで移動）': 'Timeline (click to seek)',
    '前の案に戻る': 'Previous variation', '次の案へ進む': 'Next variation',
    '設定はそのままで構成だけ再抽選（ロックした行は維持）': 'Shuffle the arrangement, keeping locked lines',
    'スタイル・雰囲気・演出・配色をまるごとランダムに（キー R）': 'Randomize style, mood, effects and colors (R)',
    '押すたびに、スタイル・雰囲気・動き・配色・構成がまるごと変わります。キーボードの': 'Each click changes the style, mood, motion, colors and arrangement. Press',
    'でも実行できます。': 'to do the same.',
    '最初の公開版のあとに追加した約350の演出・配色セット12・書体6も、おまかせやシャッフルの候補にします（オフのときは最初の公開版の演出だけ）': 'Include about 350 more effects, 12 styles and 6 fonts in random picks. Off uses the original set.',
    '提灯・はがき・障子・扇・家紋・青海波・桜の花びらなどの和風グラフィック。オフにすると、おまかせやシャッフルで選ばれません': 'Include Japanese motifs such as lanterns, postcards, shoji, fans, family crests, waves and cherry blossoms in random picks.',
    '「追加」印の手法・スタイル・書体。オフのときは、おまかせやシャッフルで最初の公開版の演出だけを使います': 'Include techniques, styles and fonts marked New in automatic picks.',
    '「和」印の手法とスタイル。オフにすると、おまかせやシャッフルでは選ばれません（追加分の判定のあとに適用。行ごとに手動で指定した場合は使えます）': 'Include techniques and styles marked JP in automatic picks. Manual selections remain available.',
    '追加分の演出も使う': 'Include new effects', '和風の演出も使う': 'Include Japanese motifs',
    'スタイルだけ別のものに': 'Change the style only', 'アクセント・ズレ色A/Bをランダムに': 'Randomize accent and offset colors',
    '動き・グリッチ・使う手法の雰囲気だけ': 'Change motion, glitch and technique mood',
    'レイアウトと動きの組み合わせだけ': 'Change the arrangement and motion only',
    '画面比': 'Aspect ratio', '解像度': 'Resolution', '画質': 'Quality',
    '通常（スタイルの背景）': 'Style background', 'グリーンバック（合成用）': 'Green screen (compositing)',
    'ブラックバック（合成用）': 'Black background (compositing)',
    'MP4 を書き出す': 'Export MP4', '書き出した動画の権利について': 'Rights to exported videos',
    'フォントの役割': 'Font roles', 'PCのフォント名（例: 游明朝）': 'Installed font name (e.g. Arial)',
    'フォントファイル（.ttf/.otf）': 'Font file (.ttf/.otf)',
    'アクセント・ズレ色': 'Accent and offset colors',
    '全シーンに適用。背景に合わせて明るさを自動調整します': 'Applies to every scene. Brightness adapts to the background.',
    '自分の色で上書き': 'Use custom colors', 'ランダムに配色': 'Randomize palette',
    '背景・文字色': 'Background and text colors', 'メインの背景と文字を自分の色にする': 'Use custom background and text colors',
    '動きを何枚/秒で描くか（出力fpsとは別）': 'Motion drawings per second (independent of export fps)',
    'フル（出力fpsのまま）': 'Full (export fps)', '2コマ打ち（12枚/秒）': 'On twos (12 drawings/s)',
    '3コマ打ち（8枚/秒）': 'On threes (8 drawings/s)',
    'スタイル次第': 'Auto (by style)', '常に表示': 'Always show', '表示しない': 'Hide',
    '同じシードなら同じ構成になります。行ごとの「再抽選」「ロック」は左の行リストから。': 'The same seed produces the same arrangement. Reroll or lock individual lines in the list on the left.',
    '手法を名前で絞り込み': 'Filter techniques by name',
    'グリーンバック／ブラックバックにすると、白い文字と演出だけを単色の背景の上に描きます（背景の模様・紙の質感・粒子・周辺減光は入りません）。プレビューにもそのまま反映されます。グリーンバックは動画編集ソフトのクロマキーで、ブラックバックは「スクリーン」合成や輝度キーで抜いて、別の映像の上に重ねられます。': 'Green screen and black background render white text and effects over a solid color, without background patterns, paper texture, particles or vignette. The preview shows the export. Use a chroma key for green or Screen blending / a luma key for black to composite over footage.',
    '曲を動画に含める': 'Include audio in video', '連番PNG（ZIP）': 'PNG sequence (ZIP)',
    '透過PNG（ZIP・背景なし）': 'Transparent PNG (ZIP)',
    '書き出した動画・画像の権利とライセンスについて': 'Rights and licenses for exported videos and images',
    '書き出しはこのブラウザの中で行われます（Chrome / Edge 推奨）。': 'Export runs in your browser (Chrome or Edge recommended).',
    'このツールで作った': 'You own the', '動画や画像（出力物）の権利は、作った人': 'videos and images you create',
    'に帰属します。': '.', '※ 使った歌詞や曲の権利は、それぞれの権利者に帰属します。': 'Lyrics and music remain the property of their respective rights holders.',
    'ツール本体は': 'The tool is released under the', 'ライセンス': 'license',
    'で公開しています。ライセンスの全文は、下の「使用しているオープンソース」にあります。': '. The full license text is under Open source software below.',
    'もとにしたソフトウェアのライセンス：': 'License of the software this tool is based on:',
    'AI で歌詞の下ごしらえ・演出の3案・ひとこと修正': 'AI: prepare lyrics, three looks, one-line edits',
    'AI に演出を3案もらう': 'Get three looks from AI',
    'AI アシストを閉じる': 'Close the AI assistant', 'AI アシスト': 'AI assistant',
    '使わなくても、ほかの機能はすべて使えます。': 'Optional. Everything else works without it. ', 'できることの説明': 'What it can do',
    '使う AI と API キー': 'AI service and API key', 'AI サービス': 'AI service',
    'モデル ID': 'Model ID', 'モデル': 'Model', 'API キーを作る': 'Get an API key', 'API キー': 'API key',
    'キーを貼り付ける': 'Paste your key', 'この端末に記憶する': 'Remember on this device',
    'オフのときは、このタブを閉じるとキーが消えます。共用の PC ではオンにしないでください': 'When off, the key is forgotten when you close this tab. Do not turn this on on a shared computer.',
    'キーを消す': 'Forget keys', 'キーを確認': 'Check key',
    '送るのは、歌詞のテキスト・ひとこと修正の文・設定の数値です。曲の音声は、「曲を使う」のボタンを押したときだけ送ります。キーは、選んだ AI サービスにだけ送ります。利用料は、そのサービスから請求されます。': 'The lyric text, your one-line instruction and setting values are sent. The song audio is sent only when you press a Use the song button. Your key goes only to the AI service you chose, which bills you for its use.',
    '曲の分析（サビの位置・雰囲気・テンポ）も使います。': 'The song analysis (where the chorus is, mood, tempo) is used too.',
    '曲を使う（Gemini だけ・試験的）': 'Use the song (Gemini only, experimental)',
    '読み込んだ曲の音声を Google Gemini に送って、歌詞の書き起こし・タイミング合わせ・曲の分析をします。時刻は目安です。ずれたら行リストで直してください。': 'Sends the loaded song audio to Google Gemini to transcribe the lyrics, time the lines or analyze the song. Times are approximate; fix them in the line list if needed.',
    '曲の音声を Google Gemini に送ることに同意する': 'I agree to send the song audio to Google Gemini',
    '送ってよい曲（自分の曲や、権利者の許可がある曲）だけに使ってください。送った音声は Google の規約に従って扱われます': 'Use only songs you may send (your own, or with the rights holder’s permission). Google handles the audio under its terms.',
    '曲から歌詞を書き起こす': 'Transcribe lyrics from the song', '歌詞のタイミングを曲に合わせる': 'Time the lyrics to the song', '曲を分析する': 'Analyze the song',
    '歌詞ではない行（作詞のクレジットや [Verse] など）を除く候補、カットの区切り、強調する語、特別な読みを提案します。': 'Suggests lines to drop (credits, [Verse] labels and the like), where to cut phrases, words to emphasize and unusual readings.',
    '歌詞の下ごしらえ': 'Prepare lyrics', '下ごしらえの案を作る': 'Suggest lyric fixes',
    '歌詞の意味から、スタイル・配色・動き・サビの見せ方を3案作ります。季節に合わないモチーフ（夏の歌に雪など）は使いません。': 'Proposes three looks (style, colors, motion and how the chorus appears) from what the lyrics mean. Motifs of another season, like snow in a summer song, are left out.',
    'AI 演出3案': 'Three looks by AI', '3案を作る': 'Propose three looks',
    'ひとこと修正の指示': 'One-line edit instruction', '例：サビをもっと派手に': 'e.g. Make the chorus bolder',
    'ひとこと修正': 'One-line edit', '変更案を作る': 'Suggest changes', 'AI の変更を元に戻す': 'Undo AI change',
    'API との通信：': 'API client: ',
    '入力した歌詞や曲は、このブラウザの中だけで処理され、サーバーには送信されません。AI 機能を使ったときだけ、歌詞のテキストと数値を、選んだ AI サービスに送ります。曲の音声は、AI の「曲を使う」機能を同意のうえで使ったときだけ、Google Gemini に送ります。': 'Your lyrics and audio are processed in this browser and are not sent to a server. Only when you use an AI feature, the lyric text and numbers are sent to the AI service you chose. The song audio is sent to Google Gemini only when you agree and use an AI Use the song feature.',
    '使用しているオープンソース': 'Open source software', 'MP4 書き出し：': 'MP4 export: ',
    'フォント：': 'Fonts: ', '配布の各書体': 'typefaces', '閉じる': 'Close',
    'かんたん': 'Simple', '詳細': 'Advanced', '開く': 'Open', '保存': 'Save',
    'AE用に書き出し': 'Export for AE', '利用について': 'About / rights',
    '記法': 'Syntax', 'プレビュー': 'Preview', '再生': 'Play', 'ループ': 'Loop',
    '前の案': 'Previous', '次の案': 'Next', 'シャッフル': 'Shuffle', 'おまかせで作る': 'Create a variation',
    'おまかせ': 'Randomize', 'いまの案': 'Current variation', 'ここだけ変える': 'Change one thing',
    'スタイル': 'Style', '配色': 'Palette', '雰囲気': 'Mood', '構成': 'Arrangement',
    '書き出し': 'Export', '縦': 'portrait', '背景': 'Background',
    '追加': 'New', '和': 'JP', '演出': 'Effects', '手法': 'Techniques',
    'コマ打ち': 'Frame stepping', 'フラッシュ': 'Flash', 'シード': 'Seed', '新しいシード': 'New seed',
    '標準': 'Standard', '最高': 'Maximum', '高': 'High', '中止': 'Cancel',
}

UI = {
    '歌詞の言語：自動判定 → ': 'Lyrics language: auto-detect → ', '歌詞の言語：': 'Lyrics language: ',
    '${S.plan.cuts.length}カット': '${S.plan.cuts.length} cuts',
    '${i + 1}行目の開始秒': 'Line ${i + 1} start time (s)',
    'スタイル': 'Style', '雰囲気': 'Mood', '配色': 'Palette',
    '構成': 'Arrangement', '演出': 'Effects', '種': ' types',
    'のフォント': ' font',
    'で書き出します（': 'at (', '）。': '). ',
    '最初の公開版のあとに追加': 'Added after the original release', '和風の演出': 'Japanese motifs',
    'フォントを読み込み中…': 'Loading fonts…', '一時停止': 'Pause', '再生': 'Play',
    'この位置にカットはありません': 'No cut at this position',
    'スタイルの既定': 'Style default', '見出し書体': 'Display font',
    '見出し': 'Display', '明朝枠': 'Serif frame', '小さな文字': 'Small text',
    '背景の切替': 'Background changes', '動きの強さ': 'Motion strength',
    'カットの細かさ': 'Cut density', '装飾の量': 'Decoration amount',
    '文字の加工': 'Text treatments', '画面効果': 'Screen effects',
    'カット間のつなぎ': 'Transitions', 'レイアウト': 'Layout', '登場': 'Entrance',
    '保持': 'Hold', '退場': 'Exit', '装飾': 'Decoration', '加工': 'Treatment',
    'カメラ': 'Camera', 'つなぎ': 'Transition', '色ズレ': 'Color offset',
    'ズレ色A': 'Offset A', 'ズレ色B': 'Offset B', 'アクセント': 'Accent',
    '文字': 'Text', '補助': 'Secondary', '背景': 'Background',
    'グリッチ': 'Glitch', '質感': 'Texture',
    'この行の構成をロック': 'Lock this line', 'この行を再抽選': 'Reroll this line',
    'レイアウト指定': 'Choose layout', '開始（秒）': 'Start (s)',
    '・手動': ' · manual', '・自動': ' · automatic', '行目の開始秒': ' start time (s)',
    '行 / ': ' lines / ', 'カット': 'cuts', '行': 'line ',
    '自動': 'Auto', 'なし': 'None', 'カスタム': 'Custom',
    'ランダム': 'Random', '案目': 'variation', 'おまかせ：': 'Randomized: ',
    '配色：アクセント・ズレ色A/Bを変更': 'Palette: changed accent and offset colors',
    '構成：レイアウトと動きを再抽選': 'Arrangement: rerolled layout and motion',
    ' 種': ' types', '・': ' · ',
    'すべてON': 'All on', 'すべてOFF': 'All off', '反転': 'Invert',
    '（追加分がオフのため、': ' (new effects are off: ', '（和風の演出がオフのため、': ' (Japanese motifs are off: ',
    '（季節に合わないため、': ' (does not fit the season: ',
    '自動では選ばれません）': 'not picked automatically)', 'おまかせでは選ばれません）': 'not picked by Randomize)',
    '春の歌': 'Spring song', '夏の歌': 'Summer song', '秋の歌': 'Autumn song', '冬の歌': 'Winter song',
    '季節なし': 'No season', '季節': 'Season',
    'グリーンバック': 'Green screen', 'ブラックバック': 'Black background',
    '白い文字と演出だけ': 'white text and effects only',
    '通常（スタイルの配色）': 'Style colors',
    'このブラウザは MP4 書き出しに対応していません（Chrome / Edge 推奨）': 'MP4 export is unavailable here (Chrome or Edge recommended)',
    'このブラウザでは ': 'This browser exports with ',
    '書き出し中はタブを開いたままにしてください。': 'Keep this tab open during export.',
    'このブラウザは動画エンコード（WebCodecs）に対応していません。Chrome / Edge の最新版で開くか、連番PNGを使ってください。': 'Video encoding (WebCodecs) is unavailable here. Try the latest Chrome or Edge, or export a PNG sequence.',
    '準備中…': 'Preparing…', '完成 ': 'Done: ', '秒': 's',
    '（保存はキャンセルされました）': ' (save canceled)', 'エラー: ': 'Error: ',
    '追加分の演出：使わない（最初の公開版の演出だけ）': 'New effects: off (original set only)',
    '追加分の演出：使う': 'New effects: on',
    '和風の演出：使わない（おまかせ・シャッフルで選ばれません）': 'Japanese motifs: off for random picks',
    '和風の演出：使う': 'Japanese motifs: on',
    'フォントを読み込めませんでした': 'Could not load the font',
    'プロジェクトを読み込めませんでした': 'Could not open the project',
    '解析中…': 'Analyzing audio…', '読み込めませんでした: ': 'Could not load: ',
    '約': 'about ', '（PC）': ' (installed)',
    '追加': 'New', '和': 'JP',
}

EXPORT = {
    'このブラウザは動画エンコード（WebCodecs）に対応していません。Chrome か Edge の最新版で開いてください。': 'Video encoding (WebCodecs) is unavailable. Open in the latest Chrome or Edge.',
    'キャンセルしました': 'Canceled', 'フレーム ': 'Frame ',
    '音声をエンコード中': 'Encoding audio', '完了': 'Done',
}

AI = {
    '動きの強さ': 'Motion strength', 'グリッチ': 'Glitch', '色ズレ': 'Color offset', '装飾の量': 'Decoration amount',
    'カットの細かさ': 'Cut density', '質感': 'Texture', '背景の切替': 'Background changes',
    'レイアウト': 'layout', '登場': 'entrance', '退場': 'exit', '保持': 'hold', '・': ', ',
    '（既定）': ' (default)', 'その他（モデル ID を入力）': 'Other (enter a model ID)',
    '料金の目安：100万トークンあたり 入力 ${i}・出力 ${o}': 'Approx. price per 1M tokens: in ${i} / out ${o}',
    '{p}・{m}': '{p} · {m}', 'API キーが未設定です': 'No API key yet',
    '{p}（{m}）に問い合わせ中': 'Asking {p} ({m})', '…{s}秒': '… {s}s',
    '入力 {i}・出力 {o} トークン': 'In {i} / out {o} tokens', '（約 ${usd} ≒ {jpy}円）': ' (about ${usd} ≈ ¥{jpy})',
    '歌詞が空です。': 'The lyrics are empty.',
    '{n}行目「{text}」': 'Line {n} “{text}”', '自動': 'auto', 'カスタム': 'Custom', 'スタイルの色': 'style colors', '指定なし': 'Not set',
    'ほかの季節のモチーフ（雪・桜・花火など）は自動では使いません': 'Motifs of other seasons (snow, cherry blossoms, fireworks…) are not picked automatically',
    '季節のモチーフ（雪・桜・花火など）は自動では使いません': 'Seasonal motifs (snow, cherry blossoms, fireworks…) are not picked automatically',
    '使う手法も雰囲気に合わせて絞ります': 'Techniques are narrowed to fit the mood',
    '季節：{from} → {to}': 'Season: {from} → {to}', 'スタイル：{from} → {to}': 'Style: {from} → {to}', '雰囲気：{from} → {to}': 'Mood: {from} → {to}',
    '{label}：{from} → {to}': '{label}: {from} → {to}', 'フラッシュ：オンにする': 'Flash: on', 'フラッシュ：オフにする': 'Flash: off',
    '配色：{from} → {to}': 'Palette: {from} → {to}', '使わない手法を {n} 個に設定': 'Leave out {n} techniques', '使う手法に {n} 個戻す': 'Bring back {n} techniques',
    '{line} の{field}：{from} → {to}': '{line}: {field} {from} → {to}',
    '{line}：フラッシュと揺れを入れる': '{line}: add flash and shake', '{line}：フラッシュと揺れを外す': '{line}: remove flash and shake',
    '{line}：「{word}」を強調': '{line}: emphasize “{word}”',
    '一覧にない手法や、季節に合わない指定など {n} 件は使いませんでした。': '{n} suggestions were skipped (unknown techniques or off-season picks).',
    'すべて選ぶ': 'Select all', 'すべて外す': 'Select none', '閉じる': 'Close',
    '下ごしらえの案（{n} 件）': 'Suggested lyric fixes ({n})', '直したほうがよい行は見つかりませんでした。': 'No lines need fixing.',
    '→ この行を除く': '→ drop this line', '選んだ変更を歌詞に反映': 'Apply selected fixes', '歌詞の下ごしらえ：{n} 件を反映しました': 'Lyric fixes: {n} applied',
    '演出の3案（季節：{season}）': 'Three looks (season: {season})', '案{n}\u3000{title}': 'Look {n}: {title}',
    '使える変更がありませんでした。': 'No usable changes.', 'この案にする': 'Use this look', '演出の案「{title}」にしました': 'Applied look “{title}”',
    '「{text}」の変更案': 'Changes for “{text}”', '変えるところが見つかりませんでした。': 'Nothing to change.',
    '指示の意味を確かめさせてください': 'Please clarify the instruction', '選んだ変更を適用': 'Apply selected changes',
    'ひとこと修正：{n} 件を適用しました': 'One-line edit: {n} changes applied',
    '案を作ったあとに歌詞が変わったため、反映できません。もう一度作ってください': 'The lyrics changed after this suggestion, so it cannot be applied. Please ask again.',
    '同じ行の繰り返し（{n} か所）すべてに入ります': 'Applies to all {n} repeats of this line',
    'AI の変更のあとに変えたところも、AI の変更の前の状態に戻ります。元に戻しますか？': 'Changes you made after the AI change will also be undone. Undo?',
    '問い合わせのあいだに歌詞が変わりました。もう一度試してください。': 'The lyrics changed while waiting for the answer. Please try again.',
    '歌詞を書き換えられませんでした。': 'Could not rewrite the lyrics.',
    '曲の音声を準備中': 'Preparing the song audio', '曲をアップロード中': 'Uploading the song', 'アップロードした曲の準備を待っています': 'Waiting for the uploaded song to be ready',
    'AI サービスで Google Gemini を選んだときだけ使えます。': 'Available only when Google Gemini is the AI service.',
    '先に「曲を読み込む」で曲を読み込んでください。': 'Import a song first with Import audio.', '使うには、上の同意にチェックを入れてください。': 'Tick the agreement above to use these.',
    '書き起こした歌詞（{n} 行）にしました': 'Replaced the lyrics with the transcription ({n} lines)', '書き起こした歌詞（{n} 行）': 'Transcribed lyrics ({n} lines)',
    '歌詞を聞き取れませんでした。': 'No lyrics could be heard.', '行ごとの時刻も入れる': 'Include a time for each line',
    '歌詞の行頭に [分:秒] の時刻が付き、その時刻で表示されます': 'Each line gets an [mm:ss] tag and appears at that time',
    'いまの歌詞は、この歌詞に置き換わります（元に戻せます）。': 'The current lyrics will be replaced (you can undo).', 'この歌詞にする': 'Use these lyrics',
    '歌詞に [分:秒] の時刻が付いているため、タイミング合わせは使えません。時刻を消してから試してください。': 'The lyrics have [mm:ss] tags, so timing is not available. Remove the tags and try again.',
    'タイミングの案（{n} 行）': 'Suggested timing ({n} lines)', '時刻を変える行はありませんでした。': 'No line times need changing.',
    '選んだ行の時刻を反映': 'Apply selected times', '{n} 行の開始時刻を合わせました': 'Timed {n} lines',
    '曲の分析': 'Song analysis', '（〜{t}）': ' (to {t})', '雰囲気：{mood}\u3000テンポ：{bpm} BPM': 'Mood: {mood}  Tempo: {bpm} BPM', '\u3000{a}〜{b}行目': '  lines {a}–{b}',
    'この分析はプロジェクトに保存し、演出3案とひとこと修正で使います。': 'This analysis is saved with the project and used by Three looks and One-line edit.',
    'この分析で演出3案を作る': 'Propose three looks from this analysis',
    'イントロ': 'Intro', 'Aメロ': 'Verse', 'Bメロ': 'Pre-chorus', 'サビ': 'Chorus', 'Cメロ': 'Bridge', '間奏': 'Interlude', 'ソロ': 'Solo', 'アウトロ': 'Outro', 'その他': 'Other',
    '曲を使う機能は、Google Gemini を選んだときだけ使えます。': 'The song features work only with Google Gemini.', '先に曲を読み込んでください。': 'Import a song first.',
    '曲をアップロードできませんでした。少し待ってから、もう一度試してください。': 'Could not upload the song. Wait a little and try again.',
    'キーを確かめています…': 'Checking the key…', 'このキーで使えます（{m}）': 'This key works ({m})',
    'キーは有効ですが、{m} は使えません。モデルを変えてください': 'The key is valid, but {m} is not available. Choose another model.',
    '（キーの形式がいつもと違います。貼り付けまちがいがないか見てください）': ' (The key looks unusual. Check that it was pasted correctly.)',
    'AI の変更を元に戻しました': 'AI change undone', 'API キーを消しました': 'API keys forgotten',
    'API キーを入れてください。': 'Enter an API key.', '書き出し中やタップ同期中は使えません。': 'Not available while exporting or tap syncing.',
    '送る内容を作れませんでした。': 'Could not prepare the request.',
    'API キーが正しくないか、使えない状態です。キーを確かめてください。': 'The API key is wrong or cannot be used. Check the key.',
    '利用の上限に達しました。少し待ってから、もう一度試してください。': 'Usage limit reached. Wait a little and try again.',
    'このモデルは使えません。モデルを変えてください。': 'This model is not available. Choose another model.',
    'AI サービスにつながりませんでした。ネットワークを確かめてください。': 'Could not reach the AI service. Check your connection.',
    'AI サービス側でエラーが起きました。少し待ってから、もう一度試してください。': 'The AI service had an error. Wait a little and try again.',
    'AI サービスが、この内容への回答を控えました。': 'The AI service declined to answer this.',
    '回答が長すぎて、途中で切れました。もう一度試してください。': 'The answer was cut off. Try again.',
    '回答を読み取れませんでした。もう一度試してください。': 'Could not read the answer. Try again.',
    '回答が空でした。もう一度試してください。': 'The answer was empty. Try again.',
    'リクエストが受け付けられませんでした。': 'The request was not accepted.',
    'Claude 用の部品を読み込めませんでした。': 'The Claude SDK is missing.',
    'この AI サービスには対応していません。': 'This AI service is not supported.',
    '中止しました。': 'Canceled.', 'うまくいきませんでした。もう一度試してください。': 'Something went wrong. Try again.',
}


def replace_copy(source, glossary):
    # Longest first protects complete phrases from shorter label replacements.
    for japanese, english in sorted(glossary.items(), key=lambda pair: -len(pair[0])):
        source = source.replace(japanese, english)
    return source


def localize_body(source):
    return replace_copy(source, BODY).replace('You own the<strong>', 'You own the <strong>')


def localize_js(source, filename):
    if filename.endswith('12_ui.js'):
        return replace_copy(source, UI)
    if filename.endswith('11_export.js'):
        return replace_copy(source, EXPORT)
    if filename.endswith('13_ai_ui.js'):
        return replace_copy(source, AI)
    return source
